spring:
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true
    username: postgres.xcgaumjhraljokdcjonh
    password: U4ND9KIC7qIloNIH
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: XTW9lz0shGtZWNgZ6fCofPQcBBg/FsdbPKfFzZSn58UMpegLJT8lD9dHNNbvaB0EzEKT4TmUo0qjE7ZZGoyZqg==
  expiration: 3600000

server:
  port: 8084

logging:
  level:
    org:
      springframework:
        security: DEBUG
